### ISSUE TITLE
Cyclic dependency on `molecule`

### ISSUE THREAD

**Issue by urbas** [pycontribs/subprocess-tee#50] opened 2021-11-05 19:22 UTC
In the nix package manager we're seeing a build failure in subprocess-tee because of the new `molecule` dependency in tests.

Just wondering if there is a special reason for why `molecule` is used in the `test_func` test? Would it be possible to change the test to use something like this?
```python
subprocess.run(["echo", "hello world"], ...)
```

The problem is that `molecule` itself seems to depend on `subprocess-tee` so we're seeing a bit of a cyclic dependency unfortunately.

Also a quick question: it looks like the test is testing the Python built-in method `subprocess.run`. Could this test maybe be removed?

**Comment by gotmax23** [comment] 2021-11-26 02:26
I am having a similar issue with Fedora. This is problematic. In general, cyclical dependencies should be avoided if at all possible.

**Comment by ssbarnea** [comment] 2021-11-27 16:33
If that dependency is only for testing, is not cyclic at all. Subprocess-tee was created to serve molecule needs and having a test with it makes perfect sense.

**Comment by urbas** [comment] 2021-11-27 17:31
I agree, testing molecule makes sense and it definitely seems to be working in the CI for you.

Unfortunately, we are forced [to disable that test in the NixOS Linux distribution](https://github.com/NixOS/nixpkgs/blob/549025bbedac9080a513507a263a6c06326be62c/pkgs/development/python-modules/subprocess-tee/default.nix#L27-L30) because its package manger detects the cycle. We can work around it, of course, and we did. But we thought it might be prudent to notify you of this and suggest a patch.

Plus it seems to be causing problems in Fedora's package management too (@gotmax23, is this a correct assumption?).

What we would like to propose is to replace `molecule` in that test with, say, `echo`. Would that not test the same thing?

**Comment by ssbarnea** [comment] 2022-11-25 00:53
Extras do not create cyclic dependencies and it is perfectly valid to use them like this. I will close this as wontfix as this is not a bug of this library but more of a bug inside the distribution testing tools.

**Closed by ssbarnea** 2022-11-25 00:53 UTC
